#!/bin/bash
###############################################
# fixLidarOffset - Create symbolic links between the "real" LIDAR range compass-point files and "adjusted"
#                  compass-point files to compensate for any misalignment between the LIDAR's zero-degree-point
#                  and the platform's (robot's) zero-degree-point.
#
# HISTORICAL INFORMATION -
#
#  2021-02-04  msipin  Stopped creating file for the 360th degree - that is a duplicate of zero degrees!
#  2021-02-06  msipin  Picked up robot-specific values from MyPins.py
###############################################

# Incorporate MyPins.py (it is a "dual-use" Python/shell-script file!)
. ./MyPins.py

# Create "adjustment directory", if it doesn't already exist
mkdir -p $ADJUSTED_DIR

# Remove any "old" adjustment files, if any
rm -f ${ADJUSTED_DIR}/[0-9][0-9][0-9]

for HDG in {0..359}
do
	echo "HDG=$HDG"
	rh=`echo $HDG | awk '{ printf "%03d",$1 }'`
	lh=`echo $RH | awk '{ printf "%03d",$1 }'`
	if [ ""$lh"" -ge "360" ]
	then
		th=`expr $lh - 360`
		lh=`echo $th | awk '{ printf "%03d",$1 }'`
	fi
	echo ln -s ${RANGE_DIR}/$lh ${ADJUSTED_DIR}/$rh
	ln -s ${RANGE_DIR}/$lh ${ADJUSTED_DIR}/$rh

	RH=`expr $RH + 1`
done

exit 0
