#!/bin/sh
###########################
# getLidar - Pickup lidar readings from /dev/shm/??? files and put them into "lidar.csv" file
###########################

# Incorporate MyPins.py (it is a "dual-use" Python/shell-script file!)
. ./MyPins.py

# Get the Lidar sensor data, starting at (possibly-compensated-for) "0 degrees"/straight ahead
FILES=`echo ${ADJUSTED_DIR}/[0-9][0-9][0-9]`

for A in `ls $FILES`
do
	cat $A
	echo
done | awk '{

if ($1 == -1) {
    $1=0
};

if (NR>1) printf("\n")

printf("%d,%0.3f",(NR-1),$1);

}' | tee lidar.csv
#}' > lidar.csv

echo

exit 0

