#!/bin/sh
##########################################
# lidarGo - A quick shell script to see if the robot should go straight, turn left or turn right.
#           Nothing more than a P.O.C. to test the usefulness of the LIDAR as an obstacle-avoidance
#           tool.
#
#  NOTE: This program *requires* that you have the "ultra_simple" program running in the background!
#
# HISTORICAL INFORMATION -
#
#  2021-01-22  msipin  Created
#  2021-01-23  msipin  Changed LIDAR threshold from 200 to 350 to give robot more time to react to obstacles.
#  2021-02-06  msipin  Read MyPins.py to pickup values, and put more over there. Saved lidar range values
#                      to filesystem for display on website
#  2021-02-07  msipin  Changed name of this program's "RANGE_DIR" variable to avoid conflict with that of the
#                      robot-specific variable used in MyPins.*.py
#  2021-02-10  msipin  Fixed bug where left results got included in forward
##########################################

# Incorporate MyPins.py (it is a "dual-use" Python/shell-script file!)
. ./MyPins.py


# IF YOU ARE USING ADJUSTED COMPASS FILES, UNCOMMENT THE FOLLOWING LINE ---
lidar_dir=$ADJUSTED_DIR		# Use "adjusted" compass points, not the "actual" Lidar compass points


# Number of files to examine between FRONT and LEFT/RIGHT
NUM_FILES=`expr $MAX_OFF_ANGLE - $FWD_OFF_ANGLE`
echo
#echo
#echo "DEBUG: NUM_FILES=$NUM_FILES"
##exit 2
echo

# Default to throwing an error
DIRECTION=$EXIT_DIR_ERROR


# Function to compute average range from a selection of files
get_avg() {

grep -v "\-1" $* | awk 'BEGIN { count=0; val=0; }{
   split($1,arr,":")
   #printf("\tDEBUG: File: %s  Val: %s\n",arr[1],arr[2]);
   count++;
   val+=int(arr[2]);
} END {
   printf("%0d",int(val/count));
}'

}

# Function to find minimum range from a selection of files
get_min() {

grep -v "\-1" $* | awk 'BEGIN { min=999999; }{
   split($1,arr,":")
   #printf("\tDEBUG: File: %s  Val: %s\n",arr[1],arr[2]);
   if ((arr[2] >= 0) && (arr[2] < min)) {
      min = arr[2];
   }
} END {
   printf("%0d",min);
}'

}

# 1) Average out the valid (-MAX_OFF_ANGLE --to-- -FWD_OF_ANGLE) valid LIDAR distance-sensor readings and call this the "left value"
files=`ls ${lidar_dir}/[0-9][0-9][0-9] | tail -${MAX_OFF_ANGLE} | head -$NUM_FILES`
left_val=`get_min $files`
echo $left_val > ${SENSOR_OUTPUT_DIR}/${LI_L}

echo "DEBUG: left_val  = $left_val"
##exit 2



# 2) Average out the valid (-FWD_OFF_ANGLE --to-- +FWD_OFF_ANGLE) valid LIDAR distance-sensor readings, and call this the "forward value"
files1=`ls ${lidar_dir}/[0-9][0-9][0-9] | head -${FWD_OFF_ANGLE}`
files2=`ls ${lidar_dir}/[0-9][0-9][0-9] | tail -${FWD_OFF_ANGLE}`
files=`echo $files1 $files2`
fwd_val=`get_min $files`
echo $fwd_val > ${SENSOR_OUTPUT_DIR}/${LI_F}

echo "DEBUG: fwd_val   = $fwd_val"
##exit 2



# 3) Average out the valid (+FWD_OFF_ANGLE --to-- +MAX_OF_ANGLE) valid LIDAR distance-sensor readings and call this the "right value"
files=`ls ${lidar_dir}/[0-9][0-9][0-9] | head -${MAX_OFF_ANGLE} | tail -$NUM_FILES`
right_val=`get_min $files`
echo $right_val > ${SENSOR_OUTPUT_DIR}/${LI_R}

echo "DEBUG: right_val = $right_val"
##exit 2
echo



# 4) If either "left value" or "right value" is closer than SIDE_THRESHOLD...
if [ ""$left_val"" -le $SIDE_THRESHOLD -o ""$right_val"" -le $SIDE_THRESHOLD ]
then
	echo "SOMETHING ON LEFT or RIGHT "


#    5a) If "left value" *AND* "right value" are closer than SIDE_THRESHOLD...
	if [ ""$left_val"" -le $SIDE_THRESHOLD -a ""$right_val"" -le $SIDE_THRESHOLD ]
	then
		echo "SOMETHING ON *BOTH* LEFT *AND* RIGHT "
#       6a) Backup a bit and turn (randomly left or right)
		echo "Need to BACK OUT"
		DIRECTION=$EXIT_DIR_BACKUP_AND_TURN
	else

#    5b) If "left value" is lower than (or equal-to) "right value"...
		if [ ""$left_val"" -le ""$right_val"" ]
		then
#       6b) Turn right
			echo "Need to turn RIGHT"
			DIRECTION=$EXIT_DIR_RIGHT
		else

#    5c) If "right value" is lower than (only!) "left value"...
			if [ ""$right_val"" -lt ""$left_val"" ]
			then
#       6c) Turn left
				echo "Need to turn LEFT"
				DIRECTION=$EXIT_DIR_LEFT
			else
				echo "STUCK 1"
				DIRECTION=$EXIT_DIR_STUCK
			fi
		fi
	fi
else
# 7) If "forward value" is greater than FWD_THRESHOLD...
	if [ ""$fwd_val"" -gt $FWD_THRESHOLD ]
	then
# 8a) It is safe to move forward
		echo "Can MOVE FORWARD"
		DIRECTION=$EXIT_DIR_FWD
	else
# 8b) Make a turn...
		if [ ""$right_val"" -le ""$left_val"" ]
		then
			echo "Turn LEFT"
			DIRECTION=$EXIT_DIR_LEFT
		else
			echo "Turn RIGHT"
			DIRECTION=$EXIT_DIR_RIGHT
		fi
	fi
fi

exit $DIRECTION


#######################################
TEST RESULTS -

DEBUG: fwd_val = 193	# CAN NOT GO FWD
DEBUG: NUM_FILES=15
DEBUG: right_val = 563  # can go LEFT
DEBUG: left_val = 220   # can go RIGHT
			## SHOULD go LEFT
STUCK 2

