#!/bin/sh
##########################################
# lidarGo - A quick shell script to see if the robot should go straight, turn left or turn right.
#           Nothing more than a P.O.C. to test the usefulness of the LIDAR as an obstacle-avoidance
#           tool.
#
#  NOTE: This program *requires* that you have the "ultra_simple" program running in the background!
#
# HISTORICAL INFORMATION -
#
#  2021-01-22  msipin  Created
##########################################

# Constants that could be returned upon exit
EXIT_DIR_UNKNOWN=0
EXIT_DIR_ERROR=1
EXIT_DIR_LEFT=2
EXIT_DIR_FWD=3
EXIT_DIR_RIGHT=4
EXIT_DIR_BACKUP_AND_TURN=400
EXIT_DIR_STUCK=404

# Default to throwing an error
DIRECTION=$EXIT_DIR_ERROR

# Where to look for range values (*MUST* MATCH the directory used in "ultra_simple"!!!)
RANGE_DIR=/dev/shm

FWD_OFF_ANGLE=30  # 0 +/- this is considered "forward-looking"
FWD_THRESHOLD=30  # If there is nothing in front of the LIDAR closer than this value, it is safe to move forward

MAX_OFF_ANGLE=45  # Beyond FWD_OFF_ANGLE and up to (this) is considered "right-" or "left-looking"
SIDE_THRESHOLD=30 # If there is something to the side of the LIDAR that is closer than this value, a turn is necessary!

# 1) Average out the valid (-FWD_OFF_ANGLE --to-- +FWD_OFF_ANGLE) valid LIDAR distance-sensor readings, and call this the "forward value"
# 2) Average out the valid (-MAX_OFF_ANGLE --to-- -FWD_OF_ANGLE) valid LIDAR distance-sensor readings and call this the "left value"
# 3) Average out the valid (+FWD_OFF_ANGLE --to-- +MAX_OF_ANGLE) valid LIDAR distance-sensor readings and call this the "right value"
# 4) If "forward value" is greater than FWD_THRESHOLD, it is safe to move forward
# 5) If either "left value" or "right value" is closer than SIDE_THRESHOLD...
#    6a) If "left value" *AND* "right value" are closer than SIDE_THRESHOLD...
#       7a) Backup a little and turn (randomly left or right)
#    6b) If "left value" is lower than "right value"...
#       7b) Turn right
#    6c) If "right value" is lower than "left value"...
#       7c) Turn left

exit $DIRECTION

